version: "3"
services:

  frontend:
    container_name: hod-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - mern-network
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/public:/frontend/public
    depends_on:
      - backend
    environment:
      - REACT_APP_SERVER=http://localhost:8800
      - CHOKIDAR_USEPOLLING=true
    command: npm run start
    stdin_open: true
    tty: true
  
  backend:
    container_name: hod-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8800:8800
    networks:
      - mern-network
    volumes:
      - ./backend/src:/backend/src
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017
      - CLIENT=http://localhost:3000
    command: /backend/node_modules/.bin/nodemon -L src/index.js

  db:
    container_name: hod-db
    image: mongo:4.0.16-xenial
    ports:
      - 27017:27017
    networks:
      - mern-network
    volumes:
      - mongo-data:/data/db

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local